version: "3.6"

networks:
  zoop-webhooks-bridge:
    name: "bridge"
    driver: bridge

volumes:
  localstack:

services:
  localstack-target:
    image: localstack/localstack:0.12.7
    hostname: localstack
    ports:
      - 8080:8080
      - 4566:4566
    environment:
      - DATA_DIR=
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - TEST_AWS_ACCOUNT_ID=111111111111
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - EDGE_PORT=443
      - SERVICES=logs,iam,lambda
      - MAIN_CONTAINER_NAME=localstack_localstack-target_1
      - AWS_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOVE_CONTAINERS=true
      - LAMBDA_DOCKER_NETWORK=bridge
    networks:
      - bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack:/tmp/localstack/data