name: Actions Workflow
on:
  push:
    branches:
      - section2
      - test
      - master
      - 'feature/*'
      - '!release/*'
    paths-ignore:
      - ".gitignore"
      - "**.md"
  repository_dispatch:
    types: [build]
  schedule:
    - cron: "0 18 * 4 SUN"
    - cron: "0 6 * * MON"
    #  push:
  pull_request:
    branches:
      - master
    types: [closed, assigned, opened, reopened]
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: |
          if [ -f random.txt ]; then
            echo "::set-output name=test::hello"
          else
            echo "::set-output name=test::hell"
          fi
      - id: step2
        run: |
          if [ -f README.md ]; then
            echo "::set-output name=test::world"
          else
            echo "::set-output name=test::on fire"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: print
        run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - name: test
        if: needs.job1.outputs.output1 == 'hello' && needs.job1.outputs.output2 == 'world'
        run: echo "It can go forward"

  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
#         git clone git$github:$GITHUB_REPOSITORY
#         git checkout $GITHUB_SHA

      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Aldo
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
