  name: Shell Commands
  on: [push]

  jobs:
    run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: echo "Going on"
        - name: multiple commands
          run: |
            node -v
            npm -v

